### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by djjudas21** [utkuozdemir/pv-migrate#2]
Hi there. I just tried to use `pv-migrate` for some tests. I'm using the binary release for x86_64 and it exploded with a panic. I don't know any Golang at all so I haven't tried to troubleshoot this. Thanks

```
[jonathan@zeus kubernetes]$ ~/bin/linux/pv-migrate --source-namespace camerahub-preprod --source media --dest-namespace camerahub-preprod --dest media2
INFO[0000] Both claims exist and bound, proceeding...   
INFO[0000] Creating sshd pod                             podName=pv-migrate-sshd-k51ey
INFO[0000] Waiting for pod to start running              podName=pv-migrate-sshd-k51ey
INFO[0004] sshd pod running                              podName=pv-migrate-sshd-k51ey
INFO[0004] Creating rsync job                            jobName=pv-migrate-rsync-k51ey
INFO[0004] Waiting for rsync job to finish               jobName=pv-migrate-rsync-k51ey
PANI[0009] Job failed, exiting                           jobName=pv-migrate-rsync-k51ey podName=pv-migrate-rsync-k51ey-j5vm9
E1130 20:32:21.167374 3459660 runtime.go:66] Observed a panic: &logrus.Entry{Logger:(*logrus.Logger)(0xc000082240), Data:logrus.Fields{"jobName":"pv-migrate-rsync-k51ey", "podName":"pv-migrate-rsync-k51ey-j5vm9"}, Time:time.Time{wall:0xbfe9739549f22e73, ext:9484508853, loc:(*time.Location)(0x1eb9b20)}, Level:0x0, Caller:(*runtime.Frame)(nil), Message:"Job failed, exiting", Buffer:(*bytes.Buffer)(nil), err:""} (&{0xc000082240 map[jobName:pv-migrate-rsync-k51ey podName:pv-migrate-rsync-k51ey-j5vm9] 2020-11-30 20:32:21.166866547 +0000 GMT m=+9.484508853 panic <nil> Job failed, exiting <nil> })
/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/Cellar/go/1.12/libexec/src/runtime/panic.go:522
/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/github.com/sirupsen/logrus/entry.go:227
/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/github.com/sirupsen/logrus/entry.go:256
/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/github.com/sirupsen/logrus/entry.go:294
/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/main.go:378
/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/client-go/tools/cache/controller.go:202
/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/client-go/tools/cache/shared_informer.go:552
/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203
/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/client-go/tools/cache/shared_informer.go:548
/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/client-go/tools/cache/shared_informer.go:546
/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/usr/local/Cellar/go/1.12/libexec/src/runtime/asm_amd64.s:1337
panic: (*logrus.Entry) (0x1227a80,0xc0003324e0) [recovered]
	panic: (*logrus.Entry) (0x1227a80,0xc0003324e0)

goroutine 45 [running]:
github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1227a80, 0xc0003324e0)
	/usr/local/Cellar/go/1.12/libexec/src/runtime/panic.go:522 +0x1b5
github.com/utkuozdemir/pv-migrate/vendor/github.com/sirupsen/logrus.Entry.log(0xc000082240, 0xc00036e120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/github.com/sirupsen/logrus/entry.go:227 +0x2ce
github.com/utkuozdemir/pv-migrate/vendor/github.com/sirupsen/logrus.(*Entry).Log(0xc000332480, 0xc000000000, 0xc000572918, 0x1, 0x1)
	/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/github.com/sirupsen/logrus/entry.go:256 +0xe4
github.com/utkuozdemir/pv-migrate/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc000332480, 0xc0005ad918, 0x1, 0x1)
	/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/github.com/sirupsen/logrus/entry.go:294 +0x55
main.createJobWaitTillCompleted.func1(0x1237160, 0xc000325c00, 0x1237160, 0xc000062a80)
	/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/main.go:378 +0x310
github.com/utkuozdemir/pv-migrate/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/client-go/tools/cache/controller.go:202
github.com/utkuozdemir/pv-migrate/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x42ac1d, 0x0, 0x0)
	/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/client-go/tools/cache/shared_informer.go:552 +0x1dd
github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0xc0005ade38, 0x42a77f, 0xc0000c4080)
	/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203 +0xde
github.com/utkuozdemir/pv-migrate/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/client-go/tools/cache/shared_informer.go:548 +0x89
github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000061f68)
	/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005adf68, 0xdf8475800, 0x0, 0x13e1101, 0xc0000a1920)
	/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
github.com/utkuozdemir/pv-migrate/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc000642500)
	/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/client-go/tools/cache/shared_informer.go:546 +0x9c
github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0000f6a00, 0xc00063ecc0)
	/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/Users/utku/go/src/github.com/utkuozdemir/pv-migrate/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
```

**Comment by utkuozdemir** [comment]
Hi 👋 
The project is largely refactored (basically rewritten). 
I know that it has been a long time since you opened the issue, but if you still need the tool, give newer versions a try and feel free to re-open if you face the same issue.
Cheers.
